<a href="https://colab.research.google.com/github/poon-nimman/data-bootcamp12/blob/main/ESS_Python_for_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python for DA

- Object Oriented Programming
- Read and Write File
- Context Manager
- Handle Error
- Pandas & Numpy (on demand)
- Request API

# **OOP**

In [13]:
class Dog:
    def __init__(self, name, species, age) :
        self.name = name
        self.species = species
        self.age = age

    def bark(self) :
        print(f"{self.name} is barking 'hong hong'!")

    def hbd(self):
        self.age += 1

In [15]:
dog1 = Dog("Buddy", "Golden Retriever", 2)
dog2 = Dog("Max", "Labrador Retriever", 3)

In [16]:
print(f"{dog2.name} is {dog1.species}")

Max is Golden Retriever

In [17]:
dog1.bark()
dog2.bark()

Buddy is barking 'hong hong'!
Max is barking 'hong hong'!

In [20]:
print(dog1.age)
dog1.hbd()
print(dog1.age)

4
5

## **OOP**
* attributes: name, species, age
* medthods: fuction bark() hbd()

In [ ]:
## homeworks OOP for an ATM

## deposit, withdrawm check balance, OTP, order coffee, pay bill, internet etc.

In [88]:
class ATM:
    def __init__(self, username, bank, amount):
       self.username = username
       self.bank = bank
       self.amount = amount

    def __str__(self):
        return f"{self.username} uses {self.bank} and has {self.amount} THB in an account."

    def check_balance(self):
        print(f"Balance: {self.amount} THB")

    def deposit(self, saving):
        self.amount += saving
        print(f"Deposit: {saving} THB successfully!")

In [85]:
poon = ATM(username="nutthaphat poon", bank="uob", amount=100)

In [86]:
print(f"{poon.username} open a new bank account at uob")

nutthaphat poon open a new bank account at uob

In [87]:
poon.check_balance()

Balance: 100 THB

In [96]:
poon.deposit(100)

Deposit: 100 THB successfully!

In [92]:
poon.check_balance()

Balance: 200 THB

In [97]:
print(poon)

nutthaphat poon uses uob and has 500 THB in an account.

In [98]:
## super class

In [103]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

## extension
class Employee(Person):
    def __init__(self, name, age, company):
        super().__init__(name, age)
        self.company = company

    def greeting(self):
        print("Hello World!")

In [105]:
person1 = ("toy", 37)

In [108]:
person2 = Employee("lida", 28, "google")

In [112]:
person2.company

'google'

## **Try Except Block**

In [113]:
try:
    result = 1/0
except:
    print("this is an error message!")

this is an error message!

In [116]:
!ls

hotel.csv  sample_data

In [117]:
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [119]:
## read file
import csv

In [134]:
##มีโอกาสชื่อไฟล์ผิด
try:
    file = open("hotel.csv", "r") ## r=read w=write a=appe

## csv.reader (original python)
    data = csv.reader(file)
    for row in data:
        print(row)
    file.close()
except FileNotFoundError:
    print("file not found, please check file name again")
finally:
    print("read file successfully")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
read file successfully

In [136]:
## context manager
read_data = []

with open("hotel.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

In [139]:
# header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [141]:
## body data
read_data[1: ]

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [147]:
## for loop to calculate avg. price per night
prices = []

for row in read_data[1: ]:
    prices.append(int(row[4])) ## -1 the last item
    ## ใช้ int เพื่อเป็น str เป็นตัวเลข

print(f"Average price per night: {sum(prices)/ len(prices)}")

Average price per night: 231.5

In [ ]:
# R Programming
##mean(data$price_per_night)

In [153]:
## modern python
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410

In [155]:
df.price_per_night.mean()

np.float64(231.5)

In [157]:
df["price_per_night"].mean()

np.float64(231.5)

## **Read & Write Files**

In [158]:
import csv

In [160]:
# wirte file + context manager
head = ["id", "name", "city"]
body = [
    [1, "CU", "Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]
with open("school.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(head) ## เขียนที่ละแถว
    writer.writerows(body) ## เติม s เขียนหลายๆ แถวพร้อมกัน

In [162]:
!ls

hotel.csv  sample_data	school.csv

In [163]:
!cat school.csv

id,name,city
1,CU,Bangkok
2,LSE,London
3,Reading,Reading

In [170]:
## modern python
import pandas as pd ## as = ตั้งชื่อให้ pandas

df = pd.read_csv("school.csv")

df.head() ## head show หัว , tail show หาง

   id     name     city
0   1       CU  Bangkok
1   2      LSE   London
2   3  Reading  Reading

In [165]:
df.to_csv("school2.csv")

In [167]:
!ls

hotel.csv  sample_data	school2.csv  school.csv

In [168]:
!cat school2.csv

,id,name,city
0,1,CU,Bangkok
1,2,LSE,London
2,3,Reading,Reading

In [171]:
# read data from internet

In [173]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

In [176]:
import pandas as pd
df_penguin = pd.read_csv(url)

In [177]:
df_penguin.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [178]:
## select column
df_penguin[["species", "island", "body_mass_g"]].head(10)

  species     island  body_mass_g
0  Adelie  Torgersen       3750.0
1  Adelie  Torgersen       3800.0
2  Adelie  Torgersen       3250.0
3  Adelie  Torgersen          NaN
4  Adelie  Torgersen       3450.0
5  Adelie  Torgersen       3650.0
6  Adelie  Torgersen       3625.0
7  Adelie  Torgersen       4675.0
8  Adelie  Torgersen       3475.0
9  Adelie  Torgersen       4250.0

In [180]:
## filter rows
df_penguin[["species", "island", "body_mass_g"]]\
.query("species == 'Adelie' and island == 'Dream'") \
.head(10)

   species island  body_mass_g
30  Adelie  Dream       3250.0
31  Adelie  Dream       3900.0
32  Adelie  Dream       3300.0
33  Adelie  Dream       3900.0
34  Adelie  Dream       3325.0
35  Adelie  Dream       4150.0
36  Adelie  Dream       3950.0
37  Adelie  Dream       3550.0
38  Adelie  Dream       3300.0
39  Adelie  Dream       4650.0

In [ ]:
## R vs. Python
## R
# df %>%
#     select() %>%
#     filter() %>%
#     arrange()

## Python
# df.select()
#     .filter()\
#     .arrange()\

In [184]:
## filter without query()
df_penguin[df_penguin['body_mass_g'] >= 4500][["species", "sex", "body_mass_g"]]

    species     sex  body_mass_g
7    Adelie    MALE       4675.0
17   Adelie    MALE       4500.0
39   Adelie    MALE       4650.0
45   Adelie    MALE       4600.0
81   Adelie    MALE       4700.0
..      ...     ...          ...
338  Gentoo  FEMALE       4925.0
340  Gentoo  FEMALE       4850.0
341  Gentoo    MALE       5750.0
342  Gentoo  FEMALE       5200.0
343  Gentoo    MALE       5400.0

[118 rows x 3 columns]

In [ ]:
## request api

# Requests

how to get data via API the easy way

In [185]:
import requests

## api endpoint
url = "https://swapi.info/api/people/1"

In [187]:
response = requests.get(url)

In [190]:
response.json()["name"]

'Luke Skywalker'

In [191]:
response.json()["height"]

'172'

In [192]:
response.json()["mass"]

'77'

In [227]:
## for loop
import time
import requests as req
characters = []

for i in range(5):
    url = f"https://swapi.info/api/people/{i+1}"
    rep = req.get(url)
    rep_json = rep.json()
    data = [rep_json["name"],
            rep_json["height"],
            rep_json["mass"]]
    characters.append(data)
    time.sleep(1)
    print(f"success: {i+1}")
print(characters)

success: 1
success: 2
success: 3
success: 4
success: 5
[['Luke Skywalker', '172', '77'], ['C-3PO', '167', '75'], ['R2-D2', '96', '32'], ['Darth Vader', '202', '136'], ['Leia Organa', '150', '49']]

In [228]:
import pandas as pd

starwars = pd.DataFrame(characters, columns = ["name", "height", "mass"])

In [229]:
starwars

             name height mass
0  Luke Skywalker    172   77
1           C-3PO    167   75
2           R2-D2     96   32
3     Darth Vader    202  136
4     Leia Organa    150   49